name: 'quickbooks'
version: '1.0'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
analysis-paths: ["analysis"]

model-defaults:
  materialized: false
  enabled: true

models:
  quickbooks:
    tables:
      materialized: true
      quickbooks_general_ledger:
        dist: id
        sort: txn_date
