name: 'quickbooks'
version: '1.0'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]
test-paths: ["test"]
analysis-paths: ["analysis"]

models:
  quickbooks:
    enabled: true
    materialized: view
    tables:
      materialized: table
      quickbooks_general_ledger:
        dist: id
        sort: txn_date
